import 'package:isar/isar.dart';

import '../models/timetable_models.dart';

// Generated by build_runner (`dart run build_runner build`).
part 'isar_entities.g.dart';

/// Isar mirror entity for [Course].
///
/// We deliberately keep persistence concerns OUT of the pure domain models so
/// their `toJson`/`fromJson` stay stable for Phase 2 cloud sharing. These
/// entities are a thin storage shell that maps to/from the domain model.
@collection
class CourseEntity {
  /// Isar's own auto-increment primary key (storage detail).
  Id isarId = Isar.autoIncrement;

  /// The domain id (a uuid). Unique + indexed so we can upsert by it.
  @Index(unique: true, replace: true)
  late String uid;

  late String name;
  String? instructor;
  String? room;
  late int color;

  CourseEntity();

  factory CourseEntity.fromModel(Course c) => CourseEntity()
    ..uid = c.id
    ..name = c.name
    ..instructor = c.instructor
    ..room = c.room
    ..color = c.color;

  Course toModel() => Course(
        id: uid,
        name: name,
        instructor: instructor,
        room: room,
        color: color,
      );
}

/// Isar mirror entity for [ClassSlot].
@collection
class ClassSlotEntity {
  Id isarId = Isar.autoIncrement;

  @Index(unique: true, replace: true)
  late String uid;

  late String courseId;

  @Index()
  late int dayOfWeek;

  late int startMinutes;
  late int endMinutes;

  ClassSlotEntity();

  factory ClassSlotEntity.fromModel(ClassSlot s) => ClassSlotEntity()
    ..uid = s.id
    ..courseId = s.courseId
    ..dayOfWeek = s.dayOfWeek
    ..startMinutes = s.startMinutes
    ..endMinutes = s.endMinutes;

  ClassSlot toModel() => ClassSlot(
        id: uid,
        courseId: courseId,
        dayOfWeek: dayOfWeek,
        startMinutes: startMinutes,
        endMinutes: endMinutes,
      );
}
