import 'package:isar/isar.dart';

// Generated by build_runner (`dart run build_runner build`).
part 'isar_entities.g.dart';

/// Single-row store for the whole [Timetable], persisted as its canonical JSON
/// string. Keeping persistence as one JSON blob means the domain model stays
/// pure and the same JSON is reused for Phase-2 cloud sharing.
@collection
class TimetableDocEntity {
  /// Fixed id — there is only ever one timetable document.
  Id id = 0;

  late String json;

  TimetableDocEntity();

  TimetableDocEntity.of(this.json);
}
