import 'package:isar/isar.dart';

// Generated by build_runner (`dart run build_runner build`).
part 'isar_entities.g.dart';

/// Single-row store for the whole [Timetable], persisted as its canonical JSON
/// string. Keeping persistence as one JSON blob means the domain model stays
/// pure and the same JSON is reused for Phase-2 cloud sharing.
@collection
class TimetableDocEntity {
  /// Fixed id — there is only ever one timetable document.
  Id id = 0;

  late String json;

  TimetableDocEntity();

  TimetableDocEntity.of(this.json);
}

/// One published community timetable. Indexed by [matchKey] (university | branch
/// | semester | section) for fast discovery lookups — the scalable shape that a
/// real backend would index identically.
@collection
class CommunityTimetableEntity {
  Id id = Isar.autoIncrement;

  @Index(unique: true, replace: true)
  late String matchKey;

  late String university;
  late String branch;
  late String semester;
  late String section;

  String? creatorName;
  String? creatorId;
  bool verified = false;
  int userCount = 1;
  late int updatedAtMs;

  /// The full timetable JSON.
  late String json;

  CommunityTimetableEntity();
}

/// Tiny single-row KV for device identity + onboarding state.
@collection
class AppPrefsEntity {
  Id id = 0;
  late String deviceId;
  bool onboarded = false;

  AppPrefsEntity();
}
